name: Periodic build for compatibility problems detection
on:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
            echo Add other actions to build,
            echo test, and deploy your project.	    
      - name: Check golang version
        run: go version
      - name: Check env
        run: env
      - name: Init
        run: make init
      - name: Test
        run: make test

